import { Save, SlidersHorizontal } from "lucide-react";
import { useEffect, useState } from "react";
import { Navigate } from "react-router-dom";
import toast from "react-hot-toast";

import MainLayout from "../layouts/MainLayout";
import { getAiConfiguration, updateAiConfiguration, updateAiRules, type AiScoringRule } from "../services/aiDailyLeadService";
import { isOwner } from "../utils/auth";

export default function AiDailyLeadConfiguration() {
  const [batchSize, setBatchSize] = useState(100); const [generationHour, setGenerationHour] = useState(2); const [rules, setRules] = useState<AiScoringRule[]>([]); const [saving, setSaving] = useState(false);
  useEffect(() => { void (async () => { try { const configuration = await getAiConfiguration(); setBatchSize(configuration.settings.batchSize); setGenerationHour(configuration.settings.generationHour); setRules(configuration.rules); } catch { toast.error("Unable to load AI configuration."); } })(); }, []);
  if (!isOwner()) return <Navigate to="/dashboard" replace />;
  async function save() { try { setSaving(true); await Promise.all([updateAiConfiguration({ batchSize, generationHour }), updateAiRules(rules.map(({ id, weight, isActive }) => ({ id, weight, isActive })))]); toast.success("AI scoring configuration saved."); } catch (error) { console.error(error); toast.error("Unable to save AI configuration."); } finally { setSaving(false); } }
  return <MainLayout><div className="mx-auto max-w-5xl"><div className="mb-8"><p className="text-xs font-semibold uppercase tracking-[.2em] text-red-300">Owner only</p><h1 className="mt-2 flex items-center gap-3 text-3xl font-bold text-white"><SlidersHorizontal className="text-red-400" />AI Daily Leads Configuration</h1><p className="mt-2 text-zinc-400">Changes apply to future batches. Existing daily batches never change.</p></div><section className="premium-surface p-6"><h2 className="text-lg font-bold text-white">Batch generation</h2><div className="mt-5 grid gap-4 sm:grid-cols-2"><label className="text-sm text-zinc-300">Batch size<input type="number" min="1" max="5000" value={batchSize} onChange={(event) => setBatchSize(Number(event.target.value))} className="mt-2 h-11 w-full rounded-xl border border-white/10 bg-black/20 px-3 text-white outline-none" /></label><label className="text-sm text-zinc-300">Daily generation hour (IST)<input type="number" min="0" max="23" value={generationHour} onChange={(event) => setGenerationHour(Number(event.target.value))} className="mt-2 h-11 w-full rounded-xl border border-white/10 bg-black/20 px-3 text-white outline-none" /></label></div></section><section className="premium-surface mt-6 overflow-hidden"><div className="border-b border-white/10 p-6"><h2 className="text-lg font-bold text-white">Scoring rules</h2><p className="mt-1 text-sm text-zinc-400">Weights and exclusions are database-driven.</p></div><div className="divide-y divide-white/10">{rules.map((rule) => <div key={rule.id} className="flex flex-col gap-3 p-4 sm:flex-row sm:items-center"><label className="flex flex-1 items-center gap-3 text-sm font-medium text-zinc-200"><input type="checkbox" checked={rule.isActive} onChange={(event) => setRules((current) => current.map((entry) => entry.id === rule.id ? { ...entry, isActive: event.target.checked } : entry))} />{rule.label}{rule.action === "EXCLUDE" && <span className="rounded-full bg-red-500/15 px-2 py-0.5 text-xs text-red-200">Exclude</span>}</label><input type="number" disabled={rule.action === "EXCLUDE"} value={rule.weight} onChange={(event) => setRules((current) => current.map((entry) => entry.id === rule.id ? { ...entry, weight: Number(event.target.value) } : entry))} className="h-10 w-28 rounded-lg border border-white/10 bg-black/20 px-3 text-white disabled:opacity-40" /></div>)}</div></section><div className="mt-6 flex justify-end"><button type="button" disabled={saving} onClick={save} className="inline-flex items-center gap-2 rounded-xl bg-red-600 px-5 py-3 font-semibold text-white transition hover:bg-red-500 disabled:opacity-50"><Save size={17} />{saving ? "Saving..." : "Save AI Configuration"}</button></div></div></MainLayout>;
}
